title: bendaws
description: This is my website. I'm a developer who messes with things until it works.
author: "bendaws"

theme: minima

base_url: /gh-pages-minima-starter
repository: b3ndaws/b3ndaws.github.io

# Minima social links
github_username: b3ndaws
twitter_username: benkabob

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%d-%m-%Y"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
